//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance
    {
        public int ID { get; set; }
        public Nullable<int> MemberID { get; set; }
        public Nullable<int> SessionID { get; set; }
        public Nullable<bool> Status { get; set; }
        public string Note { get; set; }
    
        public virtual Member Member { get; set; }
        public virtual Session Session { get; set; }
    }
}
