//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LoginManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class LoginLog
    {
        public int id { get; set; }
        public string State { get; set; }
        public string Code { get; set; }
        public string ReturnUrl { get; set; }
        public string Email { get; set; }
        public string DefaultUserName { get; set; }
        public System.DateTime date { get; set; }
    }
}
